"""ShopAssist marketplace catalog — source of truth for seeding and agent context."""

BRAND = {
    "name": "ShopAssist",
    "tagline": "Chat with local shops",
    "currency": "INR",
    "shipping": {
        "standard": "Free on orders above ₹2,999 | 4–6 business days",
        "express": "₹199 | 1–2 business days",
    },
    "returns": "30-day free returns on unworn items with tags",
    "payment": "UPI, cards, EMI, Cash on Delivery (select pincodes)",
    "support": "Chat, email, or in-store pickup at 120+ ShopAssist stores in India",
}

FOOTWEAR_MEN = [
    {"id": "FW-M-001", "name": "Ultraboost 24", "price": "₹15,999", "original_price": "₹18,999", "sport": "running", "sizes": ["7", "8", "9", "10", "11", "12"], "colors": ["Core Black", "Cloud White"], "features": ["Boost midsole", "Primeknit upper", "Continental rubber outsole"], "tags": ["running", "boost", "premium", "men", "adult", "footwear", "shoes", "sneakers", "road-running", "cardio", "fitness", "daily-trainer", "marathon", "long-distance", "primeknit", "grip", "above-15000"], "similar_ids": ["FW-M-002", "FW-M-004"]},
    {"id": "FW-M-002", "name": "Supernova Rise", "price": "₹11,999", "sport": "running", "sizes": ["7", "8", "9", "10", "11"], "colors": ["Grey Six", "Solar Red"], "features": ["Dreamstrike+ foam", "Supportive frame", "Breathable mesh"], "tags": ["running", "daily trainer", "men", "adult", "footwear", "shoes", "sneakers", "road-running", "cardio", "fitness", "daily-trainer", "marathon", "long-distance", "breathable", "supportive", "under-15000"], "similar_ids": ["FW-M-001", "FW-M-003"]},
    {"id": "FW-M-003", "name": "Adizero Boston 12", "price": "₹13,499", "sport": "running", "sizes": ["8", "9", "10", "11"], "colors": ["Lucid Lemon", "Core Black"], "features": ["Lightstrike Pro", "Energy rods", "Race-day feel"], "tags": ["running", "racing", "lightweight", "men", "adult", "footwear", "shoes", "sneakers", "road-running", "cardio", "fitness", "daily-trainer", "marathon", "long-distance", "race-day", "speed", "under-15000"], "similar_ids": ["FW-M-001", "FW-M-002"]},
    {"id": "FW-M-004", "name": "Samba OG", "price": "₹9,999", "sport": "lifestyle", "sizes": ["7", "8", "9", "10", "11", "12"], "colors": ["Cloud White / Core Black", "Collegiate Green"], "features": ["Suede toe cap", "Gum sole", "Iconic terrace style"], "tags": ["lifestyle", "classic", "casual", "men", "adult", "footwear", "shoes", "sneakers", "street-style", "streetwear", "lounge", "suede", "retro", "under-10000", "under-15000"], "similar_ids": ["FW-M-005", "FW-M-006"]},
    {"id": "FW-M-005", "name": "Gazelle Indoor", "price": "₹8,999", "sport": "lifestyle", "sizes": ["7", "8", "9", "10", "11"], "colors": ["Blue Bird", "Core Black"], "features": ["Suede upper", "Low profile", "Streetwear staple"], "tags": ["lifestyle", "retro", "men", "adult", "footwear", "shoes", "sneakers", "street-style", "streetwear", "casual", "lounge", "low-profile", "suede", "classic", "under-10000", "under-15000"], "similar_ids": ["FW-M-004", "FW-M-006"]},
    {"id": "FW-M-006", "name": "Campus 00s", "price": "₹8,499", "sport": "lifestyle", "sizes": ["7", "8", "9", "10", "11"], "colors": ["Core Black", "Grey Three"], "features": ["Chunky midsole", "Suede & leather mix", "Y2K vibe"], "tags": ["lifestyle", "chunky", "men", "adult", "footwear", "shoes", "sneakers", "street-style", "streetwear", "casual", "lounge", "suede", "leather", "retro", "classic", "under-10000", "under-15000"], "similar_ids": ["FW-M-004", "FW-M-005"]},
    {"id": "FW-M-007", "name": "Predator Elite FG", "price": "₹24,999", "sport": "football", "sizes": ["8", "9", "10", "11"], "colors": ["Solar Red / Core Black"], "features": ["Strikeprint texture", "HybridTouch upper", "FG studs"], "tags": ["football", "pro", "studs", "men", "adult", "footwear", "shoes", "sneakers", "match-day", "training", "above-15000", "premium"], "similar_ids": ["FW-M-008", "FW-M-009"]},
    {"id": "FW-M-008", "name": "Copa Pure II FG", "price": "₹14,999", "sport": "football", "sizes": ["8", "9", "10", "11"], "colors": ["Cloud White / Gold"], "features": ["Soft leather forefoot", "Comfortable fit", "Classic touch"], "tags": ["football", "leather", "men", "adult", "footwear", "shoes", "sneakers", "match-day", "training", "studs", "under-15000"], "similar_ids": ["FW-M-007", "FW-M-009"]},
    {"id": "FW-M-009", "name": "X Crazyfast.3 TF", "price": "₹6,999", "sport": "football", "sizes": ["7", "8", "9", "10", "11"], "colors": ["Team Solar Yellow"], "features": ["Turf sole", "Lightweight speed", "Budget-friendly"], "tags": ["football", "turf", "speed", "men", "adult", "footwear", "shoes", "sneakers", "match-day", "training", "lightweight", "studs", "value", "under-10000", "under-15000"], "similar_ids": ["FW-M-007", "FW-M-008"]},
    {"id": "FW-M-010", "name": "Harden Vol. 8", "price": "₹16,499", "sport": "basketball", "sizes": ["8", "9", "10", "11", "12"], "colors": ["Core Black / Lucid Blue"], "features": ["Lightstrike cushioning", "Lateral stability", "Signature hoops shoe"], "tags": ["basketball", "indoor", "men", "adult", "footwear", "shoes", "sneakers", "gym", "lightweight", "cushioned", "above-15000"], "similar_ids": ["FW-M-011"]},
    {"id": "FW-M-011", "name": "Dame 9", "price": "₹12,999", "sport": "basketball", "sizes": ["8", "9", "10", "11"], "colors": ["Iron Metallic"], "features": ["Bounce Pro", "Durable outsole", "All-court grip"], "tags": ["basketball", "value", "men", "adult", "footwear", "shoes", "sneakers", "gym", "grip", "under-15000"], "similar_ids": ["FW-M-010"]},
    {"id": "FW-M-012", "name": "Terrex Swift R3 GTX", "price": "₹14,499", "sport": "outdoor", "sizes": ["8", "9", "10", "11"], "colors": ["Core Black / Grey"], "features": ["GORE-TEX waterproof", "Trail grip", "Speed hiking"], "tags": ["hiking", "waterproof", "outdoor", "men", "adult", "footwear", "shoes", "sneakers", "trail-running", "boots", "gore-tex", "grip", "under-15000"], "similar_ids": ["FW-M-013"]},
    {"id": "FW-M-013", "name": "Terrex Free Hiker 2.0", "price": "₹16,999", "sport": "outdoor", "sizes": ["8", "9", "10", "11"], "colors": ["Focus Olive"], "features": ["Boost cushioning", "High-cut support", "Long trail days"], "tags": ["hiking", "premium", "outdoor", "men", "adult", "footwear", "shoes", "sneakers", "trail-running", "boots", "boost", "cushioned", "supportive", "above-15000"], "similar_ids": ["FW-M-012"]},
]

FOOTWEAR_WOMEN = [
    {"id": "FW-W-001", "name": "Ultraboost 24 W", "price": "₹15,999", "sport": "running", "sizes": ["4", "5", "6", "7", "8"], "colors": ["Core Black", "Bliss Pink"], "features": ["Boost cushioning", "Sock-like fit", "All-day comfort"], "tags": ["running", "boost", "women", "adult", "footwear", "shoes", "sneakers", "road-running", "cardio", "fitness", "daily-trainer", "marathon", "long-distance", "cushioned", "above-15000"], "similar_ids": ["FW-W-002", "FW-W-003"]},
    {"id": "FW-W-002", "name": "Supernova Rise W", "price": "₹11,999", "sport": "running", "sizes": ["4", "5", "6", "7", "8"], "colors": ["Silver Metallic", "Linen Green"], "features": ["Supportive ride", "Breathable upper", "Daily miles"], "tags": ["running", "support", "women", "adult", "footwear", "shoes", "sneakers", "road-running", "cardio", "fitness", "daily-trainer", "marathon", "long-distance", "breathable", "supportive", "under-15000"], "similar_ids": ["FW-W-001", "FW-W-003"]},
    {"id": "FW-W-003", "name": "Adizero SL W", "price": "₹10,999", "sport": "running", "sizes": ["4", "5", "6", "7"], "colors": ["Cloud White"], "features": ["Lightweight", "Responsive foam", "Tempo runs"], "tags": ["running", "lightweight", "women", "adult", "footwear", "shoes", "sneakers", "road-running", "cardio", "fitness", "daily-trainer", "marathon", "long-distance", "race-day", "speed", "under-15000"], "similar_ids": ["FW-W-001", "FW-W-002"]},
    {"id": "FW-W-004", "name": "Samba OG W", "price": "₹9,999", "sport": "lifestyle", "sizes": ["4", "5", "6", "7", "8"], "colors": ["Cloud White / Gum", "Wonder Clay"], "features": ["Classic silhouette", "Versatile styling", "Low profile"], "tags": ["lifestyle", "classic", "women", "adult", "footwear", "shoes", "sneakers", "street-style", "streetwear", "casual", "lounge", "low-profile", "retro", "under-10000", "under-15000"], "similar_ids": ["FW-W-005", "FW-M-004"]},
    {"id": "FW-W-005", "name": "Gazelle Bold W", "price": "₹9,499", "sport": "lifestyle", "sizes": ["4", "5", "6", "7"], "colors": ["Rose Tone", "Core Black"], "features": ["Platform midsole", "Suede upper", "Statement look"], "tags": ["lifestyle", "platform", "women", "adult", "footwear", "shoes", "sneakers", "street-style", "streetwear", "casual", "lounge", "suede", "retro", "classic", "under-10000", "under-15000"], "similar_ids": ["FW-W-004", "FW-M-005"]},
    {"id": "FW-W-006", "name": "Forum Low CL W", "price": "₹8,999", "sport": "lifestyle", "sizes": ["4", "5", "6", "7", "8"], "colors": ["Cloud White / Green"], "features": ["Velcro strap", "Retro basketball", "Street style"], "tags": ["lifestyle", "retro", "women", "adult", "footwear", "shoes", "sneakers", "street-style", "streetwear", "casual", "lounge", "under-10000", "under-15000"], "similar_ids": ["FW-W-004"]},
    {"id": "FW-W-007", "name": "Predator Accuracy.3 FG W", "price": "₹7,999", "sport": "football", "sizes": ["4", "5", "6", "7"], "colors": ["Solar Red"], "features": ["FG studs", "Grip texture", "Women's fit"], "tags": ["football", "studs", "women", "adult", "footwear", "shoes", "sneakers", "match-day", "training", "grip", "under-10000", "under-15000"], "similar_ids": ["FW-M-007", "FW-W-008"]},
    {"id": "FW-W-008", "name": "Copa Pure II FG W", "price": "₹12,999", "sport": "football", "sizes": ["4", "5", "6", "7"], "colors": ["Cloud White"], "features": ["Soft touch", "Comfortable leather", "Match ready"], "tags": ["football", "leather", "women", "adult", "footwear", "shoes", "sneakers", "match-day", "training", "studs", "under-15000"], "similar_ids": ["FW-M-008", "FW-W-007"]},
    {"id": "FW-W-009", "name": "Terrex Anylander Rain.Rdy", "price": "₹9,999", "sport": "outdoor", "sizes": ["4", "5", "6", "7", "8"], "colors": ["Magic Grey"], "features": ["Water-repellent", "Trail traction", "Lightweight hike"], "tags": ["hiking", "outdoor", "women", "adult", "footwear", "shoes", "sneakers", "trail-running", "boots", "water-resistant", "lightweight", "monsoon", "packable", "under-10000", "under-15000"], "similar_ids": ["FW-M-012", "FW-W-010"]},
    {"id": "FW-W-010", "name": "Terrex Skychaser AX5", "price": "₹11,499", "sport": "outdoor", "sizes": ["4", "5", "6", "7"], "colors": ["Focus Olive / Black"], "features": ["Steep terrain grip", "Stable chassis", "Technical trails"], "tags": ["hiking", "technical", "women", "adult", "footwear", "shoes", "sneakers", "outdoor", "trail-running", "boots", "grip", "water-resistant", "monsoon", "packable", "under-15000"], "similar_ids": ["FW-W-009", "FW-M-013"]},
]

FOOTWEAR_KIDS = [
    {"id": "FW-K-001", "name": "Ultraboost 24 Kids", "price": "₹8,999", "sport": "running", "sizes": ["1", "2", "3", "4", "5"], "age_group": "8–14 years", "colors": ["Core Black", "Cloud White"], "features": ["Boost cushioning", "Durable outsole", "School + sport"], "tags": ["running", "kids", "junior", "boys", "girls", "footwear", "shoes", "sneakers", "school", "playground", "road-running", "cardio", "fitness", "daily-trainer", "marathon", "long-distance", "boost", "cushioned", "under-10000", "under-15000"], "similar_ids": ["FW-K-002", "FW-K-003"]},
    {"id": "FW-K-002", "name": "Fortarun Kids", "price": "₹3,999", "sport": "running", "sizes": ["11", "12", "13", "1", "2"], "age_group": "5–10 years", "colors": ["Blue / Solar Red"], "features": ["Easy slip-on", "Lightweight", "Playground ready"], "tags": ["running", "kids", "value", "junior", "boys", "girls", "footwear", "shoes", "sneakers", "school", "playground", "road-running", "cardio", "fitness", "daily-trainer", "marathon", "long-distance", "lightweight", "budget", "under-5000", "under-10000", "under-15000"], "similar_ids": ["FW-K-001", "FW-K-004"]},
    {"id": "FW-K-003", "name": "Samba OG Kids", "price": "₹5,999", "sport": "lifestyle", "sizes": ["11", "12", "13", "1", "2", "3"], "age_group": "6–12 years", "colors": ["Cloud White / Black"], "features": ["Iconic style", "Everyday wear", "Mini classic"], "tags": ["lifestyle", "kids", "classic", "junior", "boys", "girls", "footwear", "shoes", "sneakers", "school", "playground", "street-style", "streetwear", "casual", "lounge", "retro", "under-10000", "under-15000"], "similar_ids": ["FW-K-004", "FW-M-004"]},
    {"id": "FW-K-004", "name": "Grand Court Kids", "price": "₹3,499", "sport": "lifestyle", "sizes": ["11", "12", "13", "1", "2"], "age_group": "5–10 years", "colors": ["White / Green"], "features": ["Court-inspired", "Easy clean", "Budget pick"], "tags": ["lifestyle", "kids", "value", "junior", "boys", "girls", "footwear", "shoes", "sneakers", "school", "playground", "street-style", "streetwear", "casual", "lounge", "budget", "under-5000", "under-10000", "under-15000"], "similar_ids": ["FW-K-003", "FW-K-002"]},
    {"id": "FW-K-005", "name": "Predator Club Kids TF", "price": "₹4,499", "sport": "football", "sizes": ["11", "12", "13", "1", "2", "3"], "age_group": "6–14 years", "colors": ["Solar Red"], "features": ["Turf sole", "Grip zones", "Academy training"], "tags": ["football", "kids", "turf", "junior", "boys", "girls", "footwear", "shoes", "sneakers", "school", "playground", "match-day", "training", "grip", "studs", "water-resistant", "monsoon", "packable", "budget", "under-5000", "under-10000", "under-15000"], "similar_ids": ["FW-K-006", "FW-M-009"]},
    {"id": "FW-K-006", "name": "X Speedportal.3 Kids FG", "price": "₹5,499", "sport": "football", "sizes": ["1", "2", "3", "4", "5"], "age_group": "8–14 years", "colors": ["Team Solar Yellow"], "features": ["FG studs", "Speed focused", "Match day"], "tags": ["football", "kids", "speed", "junior", "boys", "girls", "footwear", "shoes", "sneakers", "school", "playground", "match-day", "training", "studs", "under-10000", "under-15000"], "similar_ids": ["FW-K-005", "FW-M-009"]},
]

CLOTHING_MEN = [
    {"id": "CL-M-001", "name": "Essentials 3-Stripes Tee", "price": "₹1,799", "type": "t-shirt", "sizes": ["S", "M", "L", "XL", "XXL"], "colors": ["Black", "White", "Navy"], "features": ["100% cotton", "Classic 3-stripes", "Everyday staple"], "tags": ["casual", "basics", "men", "adult", "clothing", "apparel", "t-shirt", "cotton", "budget", "under-2000", "under-5000", "under-10000", "under-15000", "daily-trainer", "value"], "similar_ids": ["CL-M-002", "CL-M-003"]},
    {"id": "CL-M-002", "name": "Own The Run Tee", "price": "₹1,499", "type": "t-shirt", "sizes": ["S", "M", "L", "XL"], "colors": ["Grey", "Black"], "features": ["AEROREADY moisture-wicking", "Reflective details", "Running"], "tags": ["running", "performance", "men", "adult", "clothing", "apparel", "road-running", "cardio", "fitness", "daily-trainer", "t-shirt", "aeroready", "budget", "under-2000", "under-5000", "under-10000", "under-15000", "training"], "similar_ids": ["CL-M-001", "CL-M-004"]},
    {"id": "CL-M-003", "name": "Trefoil Hoodie", "price": "₹4,499", "type": "hoodie", "sizes": ["S", "M", "L", "XL", "XXL"], "colors": ["Black", "Grey", "Green"], "features": ["Fleece blend", "Kangaroo pocket", "Iconic logo"], "tags": ["lifestyle", "hoodie", "men", "adult", "clothing", "apparel", "street-style", "streetwear", "casual", "lounge", "fleece", "budget", "under-5000", "under-10000", "under-15000"], "similar_ids": ["CL-M-005", "CL-M-001"]},
    {"id": "CL-M-004", "name": "Designed 4 Running Shorts", "price": "₹2,299", "type": "shorts", "sizes": ["S", "M", "L", "XL"], "colors": ["Black", "Blue"], "features": ["Lightweight", "Inner brief", "Zip pocket"], "tags": ["running", "shorts", "men", "adult", "clothing", "apparel", "road-running", "cardio", "fitness", "daily-trainer", "lightweight", "budget", "under-5000", "under-10000", "under-15000"], "similar_ids": ["CL-M-002", "CL-M-006"]},
    {"id": "CL-M-005", "name": "Z.N.E. Premium Hoodie", "price": "₹6,999", "type": "hoodie", "sizes": ["M", "L", "XL"], "colors": ["Black", "Navy"], "features": ["Travel layer", "Premium fleece", "Athlete off-duty"], "tags": ["premium", "hoodie", "men", "adult", "clothing", "apparel", "fleece", "travel", "under-10000", "under-15000"], "similar_ids": ["CL-M-003", "CL-M-007"]},
    {"id": "CL-M-006", "name": "Train Essentials Shorts", "price": "₹1,999", "type": "shorts", "sizes": ["S", "M", "L", "XL"], "colors": ["Black", "Grey"], "features": ["Gym ready", "Drawcord waist", "Quick dry"], "tags": ["training", "gym", "men", "adult", "clothing", "apparel", "fitness", "shorts", "quick-dry", "water-resistant", "monsoon", "packable", "budget", "under-2000", "under-5000", "under-10000", "under-15000"], "similar_ids": ["CL-M-004", "CL-M-008"]},
    {"id": "CL-M-007", "name": "Tiro 24 Training Pants", "price": "₹3,499", "type": "track pants", "sizes": ["S", "M", "L", "XL", "XXL"], "colors": ["Black", "Navy"], "features": ["Slim fit", "Ankle zips", "Football training"], "tags": ["football", "training", "pants", "men", "adult", "clothing", "apparel", "match-day", "gym", "fitness", "track-pants", "water-resistant", "monsoon", "packable", "budget", "under-5000", "under-10000", "under-15000"], "similar_ids": ["CL-M-008", "CL-M-005"]},
    {"id": "CL-M-008", "name": "Essentials Fleece Joggers", "price": "₹2,799", "type": "joggers", "sizes": ["S", "M", "L", "XL"], "colors": ["Black", "Grey"], "features": ["Soft fleece", "Tapered leg", "Loungewear"], "tags": ["casual", "joggers", "men", "adult", "clothing", "apparel", "pants", "fleece", "lounge", "budget", "under-5000", "under-10000", "under-15000"], "similar_ids": ["CL-M-007", "CL-M-003"]},
    {"id": "CL-M-009", "name": "Manchester United Home Jersey 24/25", "price": "₹4,999", "type": "jersey", "sizes": ["S", "M", "L", "XL"], "colors": ["Red"], "features": ["Official club kit", "AEROREADY", "Fan edition"], "tags": ["football", "jersey", "fan", "men", "adult", "clothing", "apparel", "match-day", "training", "aeroready", "budget", "under-5000", "under-10000", "under-15000"], "similar_ids": ["CL-M-010", "CL-M-011"]},
    {"id": "CL-M-010", "name": "Real Madrid Away Jersey 24/25", "price": "₹4,999", "type": "jersey", "sizes": ["S", "M", "L", "XL"], "colors": ["Navy / Orange"], "features": ["Official club kit", "Lightweight", "Fan edition"], "tags": ["football", "jersey", "fan", "men", "adult", "clothing", "apparel", "match-day", "training", "lightweight", "budget", "under-5000", "under-10000", "under-15000"], "similar_ids": ["CL-M-009", "CL-M-011"]},
    {"id": "CL-M-011", "name": "India Cricket ODI Jersey", "price": "₹3,999", "type": "jersey", "sizes": ["S", "M", "L", "XL", "XXL"], "colors": ["Blue"], "features": ["Official BCCI fan jersey", "Breathable mesh", "National pride"], "tags": ["cricket", "jersey", "fan", "men", "adult", "clothing", "apparel", "match-day", "breathable", "budget", "under-5000", "under-10000", "under-15000"], "similar_ids": ["CL-M-009", "CL-M-010"]},
    {"id": "CL-M-012", "name": "Terrex Multi Rain.Rdy Jacket", "price": "₹8,999", "type": "jacket", "sizes": ["M", "L", "XL"], "colors": ["Black", "Olive"], "features": ["Water-repellent", "Packable hood", "Hiking shell"], "tags": ["outdoor", "jacket", "rain", "men", "adult", "clothing", "apparel", "trail-running", "hiking", "water-resistant", "packable", "monsoon", "under-10000", "under-15000"], "similar_ids": ["CL-M-013"]},
    {"id": "CL-M-013", "name": "Terrex Insulated Hooded Jacket", "price": "₹12,499", "type": "jacket", "sizes": ["M", "L", "XL"], "colors": ["Focus Olive"], "features": ["PrimaLoft insulation", "Cold weather", "Trail warmth"], "tags": ["outdoor", "jacket", "winter", "men", "adult", "clothing", "apparel", "trail-running", "hiking", "insulated", "under-15000", "monsoon"], "similar_ids": ["CL-M-012"]},
]

CLOTHING_WOMEN = [
    {"id": "CL-W-001", "name": "Essentials 3-Stripes Tee W", "price": "₹1,699", "type": "t-shirt", "sizes": ["XS", "S", "M", "L", "XL"], "colors": ["Black", "White", "Pink"], "features": ["Soft cotton", "Relaxed fit", "Daily essential"], "tags": ["casual", "basics", "women", "adult", "clothing", "apparel", "t-shirt", "cotton", "budget", "under-2000", "under-5000", "under-10000", "under-15000", "daily-trainer", "value"], "similar_ids": ["CL-W-002", "CL-M-001"]},
    {"id": "CL-W-002", "name": "Own The Run Tee W", "price": "₹1,499", "type": "t-shirt", "sizes": ["XS", "S", "M", "L"], "colors": ["Lilac", "Black"], "features": ["AEROREADY", "Slim fit", "Running"], "tags": ["running", "performance", "women", "adult", "clothing", "apparel", "road-running", "cardio", "fitness", "daily-trainer", "t-shirt", "aeroready", "budget", "under-2000", "under-5000", "under-10000", "under-15000", "training"], "similar_ids": ["CL-W-001", "CL-W-003"]},
    {"id": "CL-W-003", "name": "Fast Running Shorts W", "price": "₹1,999", "type": "shorts", "sizes": ["XS", "S", "M", "L"], "colors": ["Black", "Blue"], "features": ["Built-in brief", "Lightweight", "Race day"], "tags": ["running", "shorts", "women", "adult", "clothing", "apparel", "road-running", "cardio", "fitness", "daily-trainer", "race-day", "speed", "lightweight", "budget", "under-2000", "under-5000", "under-10000", "under-15000"], "similar_ids": ["CL-W-002", "CL-W-004"]},
    {"id": "CL-W-004", "name": "Optime Training 7/8 Leggings", "price": "₹3,499", "type": "leggings", "sizes": ["XS", "S", "M", "L", "XL"], "colors": ["Black", "Navy", "Maroon"], "features": ["High waist", "Squat-proof", "Gym + yoga"], "tags": ["training", "leggings", "gym", "women", "adult", "clothing", "apparel", "fitness", "water-resistant", "monsoon", "packable", "yoga", "budget", "under-5000", "under-10000", "under-15000"], "similar_ids": ["CL-W-005", "CL-W-006"]},
    {"id": "CL-W-005", "name": "All Me Luxe Sports Bra", "price": "₹2,499", "type": "sports bra", "sizes": ["XS", "S", "M", "L"], "colors": ["Black", "White"], "features": ["Light support", "Soft fabric", "Studio sessions"], "tags": ["training", "yoga", "women", "adult", "clothing", "apparel", "gym", "fitness", "sports-bra", "supportive", "studs", "budget", "under-5000", "under-10000", "under-15000"], "similar_ids": ["CL-W-004", "CL-W-006"]},
    {"id": "CL-W-006", "name": "Powerreact Training Sports Bra", "price": "₹2,999", "type": "sports bra", "sizes": ["XS", "S", "M", "L"], "colors": ["Black", "Red"], "features": ["High support", "Adjustable straps", "HIIT ready"], "tags": ["training", "high-impact", "women", "adult", "clothing", "apparel", "gym", "fitness", "sports-bra", "supportive", "water-resistant", "monsoon", "packable", "budget", "under-5000", "under-10000", "under-15000"], "similar_ids": ["CL-W-005", "CL-W-004"]},
    {"id": "CL-W-007", "name": "Trefoil Hoodie W", "price": "₹4,299", "type": "hoodie", "sizes": ["XS", "S", "M", "L", "XL"], "colors": ["Black", "Grey", "Lilac"], "features": ["Cropped option available", "Fleece", "Street style"], "tags": ["lifestyle", "hoodie", "women", "adult", "clothing", "apparel", "street-style", "streetwear", "casual", "lounge", "fleece", "budget", "under-5000", "under-10000", "under-15000"], "similar_ids": ["CL-M-003", "CL-W-008"]},
    {"id": "CL-W-008", "name": "Essentials Fleece Wide-Leg Pants", "price": "₹3,299", "type": "pants", "sizes": ["XS", "S", "M", "L"], "colors": ["Black", "Cream"], "features": ["Wide leg", "Comfort fit", "Loungewear trend"], "tags": ["casual", "pants", "women", "adult", "clothing", "apparel", "lounge", "budget", "under-5000", "under-10000", "under-15000"], "similar_ids": ["CL-W-007", "CL-M-008"]},
    {"id": "CL-W-009", "name": "Tiro 24 Track Pants W", "price": "₹3,199", "type": "track pants", "sizes": ["XS", "S", "M", "L"], "colors": ["Black", "Navy"], "features": ["Tapered fit", "Ankle zips", "Sporty"], "tags": ["football", "training", "women", "adult", "clothing", "apparel", "match-day", "gym", "fitness", "track-pants", "pants", "budget", "under-5000", "under-10000", "under-15000"], "similar_ids": ["CL-M-007", "CL-W-008"]},
    {"id": "CL-W-010", "name": "Terrex Xperior Light Rain Jacket W", "price": "₹7,499", "type": "jacket", "sizes": ["S", "M", "L"], "colors": ["Black", "Pink"], "features": ["Ultralight shell", "Rain.Rdy", "Trail running"], "tags": ["outdoor", "jacket", "women", "adult", "clothing", "apparel", "trail-running", "hiking", "water-resistant", "monsoon", "packable", "under-10000", "under-15000"], "similar_ids": ["CL-M-012", "CL-W-011"]},
    {"id": "CL-W-011", "name": "Cropped Adicolor Track Top", "price": "₹2,799", "type": "track top", "sizes": ["XS", "S", "M", "L"], "colors": ["Black", "White", "Green"], "features": ["Retro 3-stripes", "Zip front", "Throwback style"], "tags": ["lifestyle", "retro", "women", "adult", "clothing", "apparel", "street-style", "streetwear", "casual", "lounge", "budget", "under-5000", "under-10000", "under-15000"], "similar_ids": ["CL-W-007", "CL-W-009"]},
]

CLOTHING_KIDS = [
    {"id": "CL-K-001", "name": "Kids Essentials Tee", "price": "₹999", "type": "t-shirt", "sizes": ["5-6Y", "7-8Y", "9-10Y", "11-12Y", "13-14Y"], "colors": ["Black", "White", "Blue", "Red"], "features": ["Soft cotton", "Easy wash", "School friendly"], "tags": ["kids", "basics", "junior", "boys", "girls", "school", "clothing", "apparel", "playground", "t-shirt", "cotton", "budget", "under-2000", "under-5000", "under-10000", "under-15000", "casual", "daily-trainer", "value"], "similar_ids": ["CL-K-002", "CL-K-003"]},
    {"id": "CL-K-002", "name": "Kids Logo Hoodie", "price": "₹2,499", "type": "hoodie", "sizes": ["5-6Y", "7-8Y", "9-10Y", "11-12Y"], "colors": ["Black", "Grey", "Pink"], "features": ["Cozy fleece", "Big logo", "Playground warm"], "tags": ["kids", "hoodie", "junior", "boys", "girls", "school", "clothing", "apparel", "playground", "fleece", "budget", "under-5000", "under-10000", "under-15000"], "similar_ids": ["CL-K-001", "CL-K-004"]},
    {"id": "CL-K-003", "name": "Kids Tiro Track Pants", "price": "₹1,999", "type": "track pants", "sizes": ["5-6Y", "7-8Y", "9-10Y", "11-12Y", "13-14Y"], "colors": ["Black", "Navy"], "features": ["Football inspired", "Elastic waist", "Active kids"], "tags": ["kids", "football", "pants", "junior", "boys", "girls", "school", "clothing", "apparel", "playground", "match-day", "training", "track-pants", "budget", "under-2000", "under-5000", "under-10000", "under-15000"], "similar_ids": ["CL-K-004", "CL-K-005"]},
    {"id": "CL-K-004", "name": "Kids Designed 4 Training Shorts", "price": "₹1,299", "type": "shorts", "sizes": ["5-6Y", "7-8Y", "9-10Y", "11-12Y"], "colors": ["Black", "Blue"], "features": ["Quick dry", "Gym class ready", "Lightweight"], "tags": ["kids", "training", "junior", "boys", "girls", "school", "clothing", "apparel", "playground", "gym", "fitness", "shorts", "lightweight", "quick-dry", "water-resistant", "monsoon", "packable", "budget", "under-2000", "under-5000", "under-10000", "under-15000"], "similar_ids": ["CL-K-003", "CL-K-001"]},
    {"id": "CL-K-005", "name": "Kids Football Jersey", "price": "₹1,799", "type": "jersey", "sizes": ["5-6Y", "7-8Y", "9-10Y", "11-12Y", "13-14Y"], "colors": ["Red", "Blue", "White"], "features": ["Breathable", "Team sports", "Weekend matches"], "tags": ["kids", "football", "jersey", "junior", "boys", "girls", "school", "clothing", "apparel", "playground", "match-day", "training", "breathable", "fan", "budget", "under-2000", "under-5000", "under-10000", "under-15000"], "similar_ids": ["CL-K-003", "CL-K-006"]},
    {"id": "CL-K-006", "name": "Kids Winter Puffer Jacket", "price": "₹4,999", "type": "jacket", "sizes": ["5-6Y", "7-8Y", "9-10Y", "11-12Y"], "colors": ["Black", "Navy", "Red"], "features": ["Insulated", "Water-resistant", "Cold mornings"], "tags": ["kids", "jacket", "winter", "junior", "boys", "girls", "school", "clothing", "apparel", "playground", "insulated", "budget", "under-5000", "under-10000", "under-15000", "monsoon"], "similar_ids": ["CL-K-002", "CL-K-001"]},
]

SPORTS_EQUIPMENT = [
    {"id": "EQ-001", "name": "Tiro League Football (Size 5)", "price": "₹1,999", "category": "football", "sizes": ["Size 5"], "features": ["FIFA Quality", "Machine-stitched", "Grass & turf"], "tags": ["football", "ball", "unisex", "adult", "equipment", "match-day", "training", "turf", "budget", "under-2000", "under-5000", "under-10000", "under-15000"], "similar_ids": ["EQ-002", "EQ-003"]},
    {"id": "EQ-002", "name": "UCL Pro Football", "price": "₹4,999", "category": "football", "sizes": ["Size 5"], "features": ["Match ball", "Thermally bonded", "Pro feel"], "tags": ["football", "ball", "premium", "unisex", "adult", "equipment", "match-day", "training", "budget", "under-5000", "under-10000", "under-15000"], "similar_ids": ["EQ-001", "EQ-003"]},
    {"id": "EQ-003", "name": "Starlancer Club Football (Size 4)", "price": "₹1,499", "category": "football", "sizes": ["Size 4"], "features": ["Kids & youth", "Durable casing", "Training"], "tags": ["football", "ball", "kids", "unisex", "adult", "equipment", "match-day", "training", "water-resistant", "monsoon", "packable", "budget", "under-2000", "under-5000", "under-10000", "under-15000"], "similar_ids": ["EQ-001", "EQ-004"]},
    {"id": "EQ-004", "name": "FIFA World Cup Training Ball", "price": "₹2,999", "category": "football", "sizes": ["Size 5"], "features": ["Collector design", "Training quality", "Gift-worthy"], "tags": ["football", "ball", "fan", "unisex", "adult", "equipment", "match-day", "training", "water-resistant", "monsoon", "packable", "gifting", "budget", "under-5000", "under-10000", "under-15000"], "similar_ids": ["EQ-002", "EQ-001"]},
    {"id": "EQ-005", "name": "Pro Bounce Basketball", "price": "₹2,499", "category": "basketball", "sizes": ["Size 7"], "features": ["Indoor/outdoor", "Deep channels", "Grip composite"], "tags": ["basketball", "ball", "unisex", "adult", "equipment", "gym", "grip", "premium", "budget", "under-5000", "under-10000", "under-15000"], "similar_ids": ["EQ-006"]},
    {"id": "EQ-006", "name": "3G Speedshell Football", "price": "₹1,299", "category": "football", "sizes": ["Size 5"], "features": ["Budget pick", "Hard-wearing", "Casual kickabouts"], "tags": ["football", "ball", "value", "unisex", "adult", "equipment", "match-day", "training", "budget", "under-2000", "under-5000", "under-10000", "under-15000"], "similar_ids": ["EQ-001", "EQ-003"]},
    {"id": "EQ-007", "name": "Cricket Batting Gloves", "price": "₹3,499", "category": "cricket", "sizes": ["S", "M", "L"], "features": ["Palm cushioning", "Ventilated", "Club level"], "tags": ["cricket", "gloves", "unisex", "adult", "equipment", "match-day", "fan", "cushioned", "budget", "under-5000", "under-10000", "under-15000"], "similar_ids": ["EQ-008", "EQ-009"]},
    {"id": "EQ-008", "name": "Cricket Wicket Keeping Gloves", "price": "₹4,999", "category": "cricket", "sizes": ["M", "L"], "features": ["Web grip", "Finger protection", "Match grade"], "tags": ["cricket", "gloves", "wicketkeeper", "unisex", "adult", "equipment", "match-day", "fan", "grip", "budget", "under-5000", "under-10000", "under-15000"], "similar_ids": ["EQ-007", "EQ-009"]},
    {"id": "EQ-009", "name": "Cricket Thigh Guard", "price": "₹1,799", "category": "cricket", "sizes": ["Universal"], "features": ["Lightweight protection", "Adjustable straps", "Club cricket"], "tags": ["cricket", "protection", "unisex", "adult", "equipment", "match-day", "fan", "lightweight", "budget", "under-2000", "under-5000", "under-10000", "under-15000", "football"], "similar_ids": ["EQ-007", "EQ-010"]},
    {"id": "EQ-010", "name": "Cricket Abdominal Guard", "price": "₹899", "category": "cricket", "sizes": ["S", "M", "L"], "features": ["Essential protection", "Comfort waistband", "Starter kit"], "tags": ["cricket", "protection", "value", "unisex", "adult", "equipment", "match-day", "fan", "budget", "under-2000", "under-5000", "under-10000", "under-15000", "football"], "similar_ids": ["EQ-009", "EQ-007"]},
    {"id": "EQ-011", "name": "Training Resistance Bands Set", "price": "₹2,299", "category": "fitness", "sizes": ["Set of 3"], "features": ["Light/medium/heavy", "Home workouts", "Physio friendly"], "tags": ["fitness", "training", "home", "unisex", "adult", "equipment", "gym", "home-workout", "water-resistant", "monsoon", "packable", "budget", "under-5000", "under-10000", "under-15000"], "similar_ids": ["EQ-012", "EQ-013"]},
    {"id": "EQ-012", "name": "Yoga Mat 5mm", "price": "₹2,999", "category": "fitness", "sizes": ["Standard"], "features": ["Non-slip", "Carry strap", "Studio & home"], "tags": ["fitness", "yoga", "unisex", "adult", "equipment", "home-workout", "gym", "training", "mat", "studs", "budget", "under-5000", "under-10000", "under-15000"], "similar_ids": ["EQ-011", "EQ-013"]},
    {"id": "EQ-013", "name": "Adjustable Dumbbell Set 20kg", "price": "₹8,999", "category": "fitness", "sizes": ["20kg pair"], "features": ["Quick weight change", "Home gym", "Space saver"], "tags": ["fitness", "strength", "premium", "unisex", "adult", "equipment", "home-workout", "gym", "training", "under-10000", "under-15000"], "similar_ids": ["EQ-011", "EQ-014"]},
    {"id": "EQ-014", "name": "Jump Rope Speed", "price": "₹999", "category": "fitness", "sizes": ["Adjustable"], "features": ["Cardio", "Lightweight", "Travel friendly"], "tags": ["fitness", "cardio", "value", "unisex", "adult", "equipment", "home-workout", "gym", "training", "lightweight", "travel", "budget", "under-2000", "under-5000", "under-10000", "under-15000"], "similar_ids": ["EQ-011", "EQ-012"]},
    {"id": "EQ-015", "name": "Tiro 23 Training Backpack", "price": "₹2,999", "category": "bags", "sizes": ["30L"], "features": ["Boot compartment", "Water-resistant base", "Team sports"], "tags": ["bag", "football", "training", "unisex", "adult", "equipment", "bags", "match-day", "gym", "fitness", "travel", "backpack", "water-resistant", "monsoon", "packable", "budget", "under-5000", "under-10000", "under-15000"], "similar_ids": ["EQ-016", "EQ-017"]},
    {"id": "EQ-016", "name": "4ATHLTS Duffel Bag", "price": "₹3,499", "category": "bags", "sizes": ["55L"], "features": ["Weekend trips", "Shoe tunnel", "Gym + travel"], "tags": ["bag", "duffel", "unisex", "adult", "equipment", "bags", "travel", "training", "gym", "budget", "under-5000", "under-10000", "under-15000"], "similar_ids": ["EQ-015", "EQ-017"]},
    {"id": "EQ-017", "name": "Classic Badge of Sport Backpack", "price": "₹1,999", "category": "bags", "sizes": ["25L"], "features": ["Laptop sleeve", "Daily commute", "Minimal look"], "tags": ["bag", "lifestyle", "value", "unisex", "adult", "equipment", "bags", "street-style", "streetwear", "casual", "lounge", "travel", "training", "backpack", "budget", "under-2000", "under-5000", "under-10000", "under-15000"], "similar_ids": ["EQ-015", "EQ-016"]},
    {"id": "EQ-018", "name": "Tennis Quick Backpack", "price": "₹2,499", "category": "bags", "sizes": ["Racket compatible"], "features": ["Racket sleeve", "Ventilated pocket", "Court ready"], "tags": ["bag", "tennis", "unisex", "adult", "equipment", "bags", "match-day", "travel", "training", "backpack", "budget", "under-5000", "under-10000", "under-15000"], "similar_ids": ["EQ-015", "EQ-019"]},
    {"id": "EQ-019", "name": "Tennis Solo Ball Basket", "price": "₹1,499", "category": "tennis", "sizes": ["50 balls"], "features": ["Coaching", "Practice sessions", "Portable"], "tags": ["tennis", "training", "unisex", "adult", "equipment", "gym", "fitness", "match-day", "budget", "under-2000", "under-5000", "under-10000", "under-15000"], "similar_ids": ["EQ-020"]},
    {"id": "EQ-020", "name": "Courtjam Control Tennis Racket", "price": "₹4,999", "category": "tennis", "sizes": ["L2", "L3"], "features": ["Beginner-friendly", "Lightweight frame", "All-court"], "tags": ["tennis", "racket", "unisex", "adult", "equipment", "match-day", "lightweight", "budget", "under-5000", "under-10000", "under-15000"], "similar_ids": ["EQ-019"]},
    {"id": "EQ-021", "name": "Swim Goggles Adizero", "price": "₹1,999", "category": "swimming", "sizes": ["One size"], "features": ["Anti-fog", "Racing fit", "Pool & open water"], "tags": ["swimming", "goggles", "unisex", "adult", "equipment", "fitness", "anti-fog", "lightweight", "race-day", "speed", "budget", "under-2000", "under-5000", "under-10000", "under-15000"], "similar_ids": ["EQ-022"]},
    {"id": "EQ-022", "name": "Swim Cap Silicone", "price": "₹699", "category": "swimming", "sizes": ["One size"], "features": ["Durable silicone", "Club swimming", "Essential add-on"], "tags": ["swimming", "value", "unisex", "adult", "equipment", "fitness", "budget", "under-2000", "under-5000", "under-10000", "under-15000"], "similar_ids": ["EQ-021"]},
    {"id": "EQ-023", "name": "Shin Guards X Pro", "price": "₹1,499", "category": "football", "sizes": ["S", "M", "L"], "features": ["Ankle protection", "Lightweight shell", "Match legal"], "tags": ["football", "protection", "unisex", "adult", "equipment", "match-day", "training", "ball", "lightweight", "budget", "under-2000", "under-5000", "under-10000", "under-15000", "cricket"], "similar_ids": ["EQ-024", "EQ-001"]},
    {"id": "EQ-024", "name": "Football Socks Team 3-Pack", "price": "₹999", "category": "football", "sizes": ["S", "M", "L"], "features": ["Cushioned footbed", "Arch support", "Bundle value"], "tags": ["football", "accessories", "value", "unisex", "adult", "equipment", "match-day", "training", "ball", "socks", "cushioned", "supportive", "budget", "under-2000", "under-5000", "under-10000", "under-15000"], "similar_ids": ["EQ-023", "EQ-001"]},
]

BUNDLES = [
    {"id": "BDL-001", "name": "Run Ready Bundle", "price": "₹16,999", "original_price": "₹19,497", "items": ["FW-M-002 Supernova Rise", "CL-M-002 Own The Run Tee", "CL-M-004 Running Shorts"], "audience": "men", "tags": ["running", "bundle", "road-running", "cardio", "fitness", "daily-trainer", "men", "adult", "footwear", "clothing", "above-15000"]},
    {"id": "BDL-002", "name": "Football Starter Kit", "price": "₹9,999", "original_price": "₹12,497", "items": ["FW-M-009 X Crazyfast.3 TF", "CL-M-007 Tiro 24 Pants", "EQ-001 Tiro League Ball", "EQ-023 Shin Guards"], "audience": "men", "tags": ["football", "bundle", "value", "match-day", "training", "men", "adult", "under-10000", "under-15000"]},
    {"id": "BDL-003", "name": "Women's Gym Essentials", "price": "₹7,499", "original_price": "₹8,997", "items": ["CL-W-004 Optime Leggings", "CL-W-006 Powerreact Sports Bra", "EQ-012 Yoga Mat"], "audience": "women", "tags": ["training", "bundle", "gym", "fitness", "women", "adult", "yoga", "clothing", "under-10000", "under-15000"]},
    {"id": "BDL-004", "name": "Kids Football Pack", "price": "₹8,999", "original_price": "₹10,796", "items": ["FW-K-005 Predator Club Kids TF", "CL-K-005 Kids Football Jersey", "EQ-003 Starlancer Size 4 Ball"], "audience": "kids", "tags": ["kids", "football", "bundle", "match-day", "training", "junior", "boys", "girls", "school", "footwear", "clothing", "equipment", "ball", "playground", "under-10000", "under-15000"]},
    {"id": "BDL-005", "name": "Street Style Duo", "price": "₹16,499", "original_price": "₹18,998", "items": ["FW-M-004 Samba OG", "CL-M-003 Trefoil Hoodie"], "audience": "men", "tags": ["lifestyle", "bundle", "street-style", "streetwear", "casual", "lounge", "men", "adult", "footwear", "clothing", "above-15000"]},
]


def build_marketplace_document() -> dict:
    """Build the full marketplace document for MongoDB."""
    return {
        "brand": BRAND,
        "catalog": {
            "footwear": {
                "men": FOOTWEAR_MEN,
                "women": FOOTWEAR_WOMEN,
                "kids": FOOTWEAR_KIDS,
            },
            "clothing": {
                "men": CLOTHING_MEN,
                "women": CLOTHING_WOMEN,
                "kids": CLOTHING_KIDS,
            },
            "sports_equipment": SPORTS_EQUIPMENT,
            "bundles": BUNDLES,
        },
    }


def flatten_catalog(doc: dict) -> list[dict]:
    """Flat list of every product from a marketplace document."""
    catalog = doc.get("catalog", {})
    products = []
    footwear = catalog.get("footwear", {})
    for audience, items in footwear.items():
        for p in items:
            products.append({**p, "category": "footwear", "audience": audience})
    clothing = catalog.get("clothing", {})
    for audience, items in clothing.items():
        for p in items:
            products.append({**p, "category": "clothing", "audience": audience})
    for p in catalog.get("sports_equipment", []):
        products.append({
            **p,
            "category": "sports_equipment",
            "equipment_type": p.get("category"),
            "audience": "unisex",
        })
    for p in catalog.get("bundles", []):
        products.append({**p, "category": "bundle"})
    return products


def all_products() -> list[dict]:
    """Load products from MongoDB when available, else in-memory catalog."""
    try:
        from catalog.shopassist_data import all_products as db_products
    except ImportError:
        from catalog.shopassist_data import all_products as db_products
    return db_products()
